import jsPDF from 'jspdf';

export const downloadPDF = (elementId, fileName = "Resume-Analysis.pdf") => {
  const element = document.getElementById(elementId);
  if (!element) return;

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);

  // 1. Clean the text (Remove the Emojis that cause the Ø=Þ symbols)
  // This regex removes emojis and non-standard symbols
// This version strips EVERYTHING except standard letters, numbers, and basic punctuation
  const cleanText = (text) => {
    return text.replace(/[^\x20-\x7E\n]/g, ''); 
  };

  const rawText = element.innerText;
  const lines = cleanText(rawText).split('\n').filter(line => line.trim() !== "");

  // 2. Setup PDF Styles
  let cursorY = 20;

  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(37, 99, 235); // Resumify Blue
  doc.text("Resumify.ai", margin, cursorY);
  
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text("PROFESSIONAL RESUME ANALYSIS REPORT", margin + 120, cursorY - 2);
  
  cursorY += 15;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, cursorY, pageWidth - margin, cursorY);
  cursorY += 15;

  // 3. Loop through lines and style based on content
  doc.setTextColor(40, 40, 40);
  
  lines.forEach((line) => {
    // Check if it's a Header (All caps or starts with specific words)
    const isHeader = /^(STRENGTHS|AREAS FOR IMPROVEMENT|RECOMMENDED KEYWORDS|EXECUTIVE SUMMARY|ATS SCORE)/i.test(line.trim());

    if (isHeader) {
      cursorY += 5;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.setTextColor(30, 41, 59);
    } else {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(71, 85, 105);
    }

    // Split text to fit page width
    const textLines = doc.splitTextToSize(line.trim(), contentWidth);
    
    // Check for page overflow
    if (cursorY + (textLines.length * 7) > 280) {
      doc.addPage();
      cursorY = 20;
    }

    doc.text(textLines, margin, cursorY);
    cursorY += (textLines.length * 7);

    if (isHeader) cursorY += 2; // Extra space after headers
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(180, 180, 180);
  doc.text("Generated by Resumify.ai using Gemini 2.0 AI Engine", margin, 285);

  doc.save(fileName);
};